apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "petshop.fullname" . }}
  labels:
    {{- include "petshop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "petshop.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "petshop.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "petshop.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-api
              containerPort: 5000
              protocol: TCP
            - name: http-internal
              containerPort: 5501
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
          livenessProbe:
            httpGet:
              path: /liveness
              port: internal
          # TODO: Disabled until postgres available
          # readinessProbe:
          #   httpGet:
          #     path: /readiness
          #     port: internal
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          secret:
            secretName: {{ include "petshop.fullname" . }}
            items:
              - key: config.toml
                path: config.toml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
