apiVersion: v1
kind: Secret
metadata:
  name: {{ include "petshop.fullname" . }}
  labels:
    {{- include "petshop.labels" . | nindent 4 }}
type: Opaque
# TODO: More configuration options from values here
stringData:
  config.toml: |-
    tracing_json = true
    api_host = "0.0.0.0"
    api_port = 5000
    internal_host = "0.0.0.0"
    internal_port = 5501
    metrics_name = {{ .Values.config.metrics_name | default "petshop_server" | quote }}

    [csrf]
    cookie_name = "XSRF-TOKEN"
    cookie_domain = "localhost"
    cookie_path = "/"
    cookie_secure = true
    cookie_samesite = "strict"
    cookie_max_age_minutes = 1440
    header_name = "X-XSRF-TOKEN"
    allow_origins = [
        "http://localhost"
    ]
    token_length = {{ .Values.config.csrf.token_length | default 32 }}

    [postgres]
    user = {{ .Values.config.postgres.user | quote }}
    password = {{ .Values.config.postgres.password | quote }}
    dbname = {{ .Values.config.postgres.dbname | quote }}
    host = {{ .Values.config.postgres.host | quote }}
    port = {{ .Values.config.postgres.port }}

  envoy.yaml: |-
    admin:
      access_log_path: /dev/null
      address:
        socket_address: { address: 0.0.0.0, port_value: 9901 }
    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address: { address: 0.0.0.0, port_value: 10000 }
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    codec_type: AUTO
                    stat_prefix: {{ include "petshop.fullname" . }}
                    use_remote_address: true
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: upstream
                          domains: ["*"]
                          routes:
                            - match: { prefix: "/" }
                              route: { cluster: petshop, timeout: { seconds: 60 } }
                          cors:
                            allow_origin_string_match: { prefix: "*" }
                            allow_methods: POST, OPTIONS
                            allow_headers: authorization,keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,x-xsrf-token
                            expose_headers: grpc-status,grpc-message
                            allow_credentials: true
                    http_filters:
                      - name: envoy.filters.http.cors
                      - name: envoy.filters.http.grpc_web
                      - name: envoy.filters.http.grpc_json_transcoder
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
                          proto_descriptor: "/data/api.pb"
                          services: ["grpc.health.v1.Health", "api.Petshop", "api.Tfb"]
                          print_options:
                            add_whitespace: true
                            always_print_primitive_fields: true
                            always_print_enums_as_ints: false
                            preserve_proto_field_names: false
                      - name: envoy.filters.http.router
      clusters:
        - name: petshop
          connect_timeout: 0.25s
          type: STRICT_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          typed_extension_protocol_options:
            envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
              "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
              explicit_http_config:
                http2_protocol_options: {}
          load_assignment:
            cluster_name: petshop
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: {{ include "petshop.serverName" . }}
                          port_value: 5000
