apiVersion: v1
kind: Service
metadata:
  name: {{ include "petshop.fullname" . }}
  labels:
    {{- include "petshop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.api_port }}
      targetPort: http-api
      protocol: TCP
      name: http-api
    - port: {{ .Values.service.internal_port }}
      targetPort: http-internal
      protocol: TCP
      name: http-internal
  selector:
    {{- include "petshop.selectorLabels" . | nindent 4 }}
