apiVersion: v1
kind: Service
metadata:
  name: {{ include "petshop.serverName" . }}
  labels:
    {{- include "petshop.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "petshop.serverSelectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "petshop.envoyName" . }}
  labels:
    {{- include "petshop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "petshop.envoySelectorLabels" . | nindent 4 }}
