tracing_json = true
api_host = "0.0.0.0"
api_port = 5000
internal_host = "0.0.0.0"
internal_port = 5501

[postgres]
user = "postgres"
password = "postgres"
dbname = "postgres"
host = "postgres"
port = 5432
