tracing_json = true
api_host = "0.0.0.0"
api_port = 5000
internal_host = "0.0.0.0"
internal_port = 5501
metrics_name = "petshop_server"

[csrf]
cookie_name = "XSRF-TOKEN"
cookie_domain = "localhost"
cookie_path = "/"
cookie_secure = true
cookie_samesite = "strict"
cookie_max_age_minutes = 1440
header_name = "X-XSRF-TOKEN"
token_length = 32

[postgres]
user = "postgres"
password = "postgres"
dbname = "postgres"
host = "postgres"
port = 5432
