version: "3"
services:
  # Envoy service
  envoy:
    build:
      context: .
      dockerfile: ./docker/envoy-compose.dockerfile
    image: petshop/envoy-compose:latest
    ports:
      - 10000:10000
      - 9901:9901

  # Server service
  server:
    build:
      context: .
      dockerfile: ./docker/server.dockerfile
    image: petshop/server:latest
    ports:
      - 5000:5000
      - 5501:5501
