version: "3"
services:
  # Envoy service
  envoy:
    build:
      context: .
      dockerfile: ./docker/envoy.dockerfile
    image: petshop/envoy:latest
    ports:
      - 10000:10000
      - 9901:9901

  # Prometheus service
  prometheus:
    build:
      context: .
      dockerfile: ./docker/prometheus.dockerfile
    image: petshop/prometheus:latest
    ports:
      - 9090:9090

  # Server service
  server:
    build:
      context: .
      dockerfile: ./docker/server.dockerfile
    image: petshop/server:latest
    ports:
      - 5000:5000
      - 5501:5501

  # Client playground service
  client-playground:
    build:
      context: .
      dockerfile: ./docker/client-playground.dockerfile
    image: petshop/client-playground:latest
    ports:
      - 1234:1234
