# TODO: Running in k8s examples?
# TODO: OAuth2-proxy multiple provider support, html templates? (metrics support after next release)
# TODO: Envoy MTLS authentication example(s), other options for auth?

# TODO: Add examples for rust tests/examples/benches?
# TODO: Rust docs output in dist? cargo make --no-workspace docs-flow
# TODO: Openapi doc generator from specification?
# TODO: Read the docs docker image for docs?
# <https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html#quick-start-video>

# Build docker image tasks

[tasks.docker-build-go-tools]
category = "Petshop"
workspace = false
script = '''
echo Building petshop/go-tools:latest
docker build --tag petshop/go-tools:latest --file docker/go-tools.dockerfile .
'''

[tasks.docker-build-node-tools]
category = "Petshop"
workspace = false
script = '''
echo Building petshop/node-tools:latest
docker build --tag petshop/node-tools:latest --file docker/node-tools.dockerfile .
'''

[tasks.docker-build-rust-tools]
category = "Petshop"
workspace = false
script = '''
echo Building petshop/rust-tools:latest
docker build --tag petshop/rust-tools:latest --file docker/rust-tools.dockerfile .
'''

[tasks.docker-build-rust-cache]
category = "Petshop"
workspace = false
script = '''
echo Building petshop/rust-cache:latest
docker build --tag petshop/rust-cache:latest --file docker/rust-cache.dockerfile .
'''

# FIXME: BUILD_VERSION is used here for consistency with the server image,
# it might make more sense to remove it and use the envoy version
[tasks.docker-build-envoy]
category = "Petshop"
workspace = false
script = '''
echo Building petshop/envoy:latest
docker build --tag petshop/envoy:latest \
    --label org.opencontainers.image.version="${BUILD_VERSION}" \
    --label org.opencontainers.image.created="$(date --rfc-3339=seconds --utc)" \
    --label org.opencontainers.image.revision="$(git rev-parse HEAD)" \
    --file docker/envoy.dockerfile .
docker build --tag petshop/envoy-localhost:latest --file docker/envoy-localhost.dockerfile .
'''

[tasks.docker-build-client-playground]
category = "Petshop"
workspace = false
script = '''
echo Building petshop/client-playground:latest
docker build --tag petshop/client-playground:latest --file docker/client-playground.dockerfile .
'''

[tasks.docker-build-integration-test]
category = "Petshop"
workspace = false
script = '''
echo Building petshop/integration-test:latest
docker build --tag petshop/integration-test:latest --file docker/integration-test.dockerfile .
'''

[tasks.docker-build-oauth2-proxy]
category = "Petshop"
workspace = false
script = '''
echo Building petshop/oauth2-proxy:latest
docker build --tag petshop/oauth2-proxy:latest --file docker/oauth2-proxy.dockerfile .
'''

[tasks.docker-build-prometheus]
category = "Petshop"
workspace = false
script = '''
echo Building petshop/prometheus:latest
docker build --tag petshop/prometheus:latest --file docker/prometheus.dockerfile .
'''

# FIXME: BUILD_VERSION is empty when building for development, but is defined
# when running in the GitHub CI action
[tasks.docker-build-server]
category = "Petshop"
workspace = false
script = '''
echo Building petshop/server:latest
docker build --tag petshop/server:latest \
    --label org.opencontainers.image.version="${BUILD_VERSION}" \
    --label org.opencontainers.image.created="$(date --rfc-3339=seconds --utc)" \
    --label org.opencontainers.image.revision="$(git rev-parse HEAD)" \
    --file docker/server.dockerfile .
'''

[tasks.docker-build-tools]
description = "Build docker tools images that do not rely on generated outputs"
category = "Petshop"
workspace = false
dependencies = [
    "docker-build-go-tools",
    "docker-build-rust-tools"
]

[tasks.docker-build]
description = "Build docker images that do not rely on generated outputs"
category = "Petshop"
workspace = false
dependencies = [
    "docker-build-tools",
    "docker-build-rust-cache",
    "docker-build-prometheus",
    "docker-build-server"
]

# Run docker container tools

[tasks.go-tools-run]
description = "Run go-tools image with arguments"
category = "Petshop"
workspace = false
script = '''
echo Running petshop/go-tools:latest
docker run --rm -v "$(pwd):/src" --user "$(id -u):$(id -g)" petshop/go-tools:latest ${@}
'''

[tasks.node-tools-run]
description = "Run node-tools image with arguments"
category = "Petshop"
workspace = false
script = '''
echo Running petshop/node-tools:latest
docker run --rm -v "$(pwd)/docker/node-tools/client-playground:/home/node/client-playground" \
    -v "$(pwd)/docker/node-tools/integration-test:/home/node/integration-test" \
    -v "$(pwd)/dist:/home/node/dist" \
    -v "$(pwd)/proto/proto:/home/node/proto" \
    --user "$(id -u):$(id -g)" petshop/node-tools:latest ${@}
'''

# Run docker container tools interactively

[tasks.go-tools]
description = "Run go-tools image interactively"
category = "Petshop"
workspace = false
script = '''
echo Running petshop/go-tools:latest
docker run --rm -it -v "$(pwd):/src" --user "$(id -u):$(id -g)" --network=host petshop/go-tools:latest ${@}
'''

[tasks.node-tools]
description = "Run node-tools image interactively"
category = "Petshop"
workspace = false
script = '''
echo Running petshop/node-tools:latest
docker run --rm -it -v "$(pwd)/docker/node-tools/client-playground:/home/node/client-playground" \
    -v "$(pwd)/docker/node-tools/integration-test:/home/node/integration-test" \
    -v "$(pwd)/dist:/home/node/dist" \
    -v "$(pwd)/proto/proto:/home/node/proto" \
    --user "$(id -u):$(id -g)" --network=host petshop/node-tools:latest ${@}
'''

[tasks.rust-tools]
description = "Run rust-tools image interactively"
category = "Petshop"
workspace = false
script = '''
echo Running petshop/rust-tools:latest
docker run --rm -it -v "$(pwd):/src" --user "$(id -u):$(id -g)" --network=host petshop/rust-tools:latest ${@}
'''

# Protobuf/openapi generator tasks

[tasks.generate-protoc-protobuf]
description = "Generate protobuf descriptor file"
category = "Petshop"
workspace = false
script = '''
echo Generating protobuf descriptor set dist/data/api.pb
mkdir -p ./dist/data
cargo make go-tools-run -- protoc -I/usr/local/include -I/go/src -I/src/proto/proto \
    --include_imports --include_source_info \
    --descriptor_set_out=/src/dist/data/api.pb /src/proto/proto/api.proto /src/proto/proto/health.proto

rm -rf ./examples/tfb/api.pb
cp ./dist/data/api.pb ./examples/tfb/api.pb
'''

[tasks.generate-protoc-openapi]
description = "Generate openapi definition file"
category = "Petshop"
workspace = false
script = '''
echo Generating openapi v2 specification dist/data/api.swagger.json
mkdir -p ./dist/data
cargo make go-tools-run -- protoc -I/usr/local/include -I/go/src -I/src/proto/proto \
    --openapiv2_out /src/dist/data --openapiv2_opt \
    logtostderr=true /src/proto/proto/api.proto
'''

[tasks.generate-axios-client]
description = "Generate axios client"
category = "Petshop"
workspace = false
script = '''
echo Generating axios client dist/axios
rm -rf ./dist/axios
mkdir -p ./dist/axios
# DEPEND: docker pull openapitools/openapi-generator-cli:v5.0.1
# <https://hub.docker.com/r/openapitools/openapi-generator-cli>
docker run --rm -v "$(pwd):/workspace" --user "$(id -u):$(id -g)" openapitools/openapi-generator-cli:v5.0.1 \
    generate -i /workspace/dist/data/api.swagger.json \
    -g typescript-axios \
    -o /workspace/dist/axios
(cd ./dist/axios \
    && rm -rf .openapi-generator .gitignore .npmignore .openapi-generator-ignore git_push.sh)
mkdir -p ./docker/node-tools/clients
rm -rf ./docker/node-tools/clients/axios
cp -r ./dist/axios ./docker/node-tools/clients/axios
'''

[tasks.generate-grpc-web-client]
description = "Generate grpc-web client"
category = "Petshop"
workspace = false
script = '''
echo Generating grpc-web client dist/grpc-web
rm -rf ./dist/grpc-web
mkdir -p ./dist/grpc-web
cargo make go-tools-run -- protoc -I/usr/local/include -I/go/src -I/src/proto/proto \
    --js_out=import_style=commonjs:/src/dist/grpc-web \
    --grpc-web_out=import_style=commonjs+dts,mode=grpcwebtext:/src/dist/grpc-web \
    /src/proto/proto/api.proto \
    /src/proto/proto/google/api/annotations.proto \
    /src/proto/proto/google/api/field_behavior.proto \
    /src/proto/proto/google/api/http.proto \
    /src/proto/proto/google/api/httpbody.proto \
    /src/proto/proto/protoc-gen-openapiv2/options/annotations.proto \
    /src/proto/proto/protoc-gen-openapiv2/options/openapiv2.proto
mkdir -p ./docker/node-tools/clients
rm -rf ./docker/node-tools/clients/grpc-web
cp -r ./dist/grpc-web ./docker/node-tools/clients/grpc-web
'''

[tasks.generate-ng-swagger-client]
description = "Generate angular client"
category = "Petshop"
workspace = false
script = '''
echo Generating ng client dist/ng-swagger
rm -rf ./dist/ng-swagger
mkdir -p ./dist/ng-swagger
cargo make node-tools-run -- ng-swagger-gen -i /home/node/dist/data/api.swagger.json -o /home/node/dist/ng-swagger
cp ./docker/node-tools/ng-swagger/api-interceptor.ts ./dist/ng-swagger/api-interceptor.ts
'''

# FIXME: Prepends @ts-nocheck to file that causes tsc errors but is
# not used in the outputs so safe to ignore (openapiv2 annotations)
[tasks.generate-ngx-grpc-client]
description = "Generate angular client"
category = "Petshop"
workspace = false
script = '''
echo Generating ng client dist/ngx-grpc
rm -rf ./dist/ngx-grpc
mkdir -p ./dist/ngx-grpc
cargo make node-tools-run -- protoc -I/usr/local/include -I/home/node/proto \
    --plugin=protoc-gen-ng=/usr/local/bin/protoc-gen-ng \
    --ng_out=/home/node/dist/ngx-grpc /home/node/proto/api.proto

echo "// @ts-nocheck" | cat - ./dist/ngx-grpc/protoc-gen-openapiv2/options/openapiv2.pb.ts > /tmp/out \
    && mv /tmp/out ./dist/ngx-grpc/protoc-gen-openapiv2/options/openapiv2.pb.ts
'''

[tasks.generate-envoy-flow]
description = "Build generated envoy outputs"
category = "Petshop"
workspace = false
dependencies = [
    "generate-protoc-protobuf",
    "docker-build-envoy"
]

[tasks.generate-client-flow-pre]
description = "Build generated client outputs"
category = "Petshop"
workspace = false
dependencies = [
    "generate-protoc-openapi",
    "docker-build-node-tools",
    "generate-axios-client",
    "generate-grpc-web-client",
    "generate-ng-swagger-client",
    "generate-ngx-grpc-client"
]

[tasks.generate-client-flow]
description = "Build docker images requiring generated client outputs"
category = "Petshop"
workspace = false
dependencies = [
    "generate-client-flow-pre",
    "docker-build-client-playground",
    "docker-build-integration-test",
    "docker-build-oauth2-proxy"
]

[tasks.generate-flow]
description = "Build generated outputs"
category = "Petshop"
workspace = false
dependencies = [
    "generate-envoy-flow",
    "generate-client-flow"
]

# Development tasks

[tasks.dev-envoy]
description = "Build and run envoy docker image"
category = "Petshop"
workspace = false
dependencies = [
    "generate-envoy-flow"
]
script = '''
echo Running petshop/envoy-localhost:latest
docker run --rm -it --network=host petshop/envoy-localhost:latest
'''

[tasks.dev-postgres]
description = "Run postgres docker image"
category = "Petshop"
workspace = false
script = '''
echo Running postgres:13.2-alpine
docker run --rm -it --network=host -e POSTGRES_PASSWORD=postgres postgres:13.2-alpine
'''

[env]
RUST_LOG = "petshop_server=debug,tokio_postgres=debug"
CONFIG_TRACING_JSON = "false"
CONFIG_API_HOST = "0.0.0.0"
CONFIG_API_PORT = "5000"
CONFIG_INTERNAL_HOST = "0.0.0.0"
CONFIG_INTERNAL_PORT = "5501"
CONFIG_METRICS_NAME = "petshop_server"
CONFIG_CSRF__COOKIE_DOMAIN = "localhost"
CONFIG_CSRF__ALLOW_ORIGIN = "http://localhost"
CONFIG_POSTGRES__USER = "postgres"
CONFIG_POSTGRES__PASSWORD = "postgres"
CONFIG_POSTGRES__DBNAME = "postgres"
CONFIG_POSTGRES__HOST = "localhost"
CONFIG_POSTGRES__PORT = "5432"

[tasks.dev-server]
description = "Build and run server"
category = "Petshop"
workspace = false
script = '''
echo Running petshop_server
cargo run --bin petshop_server -- ${@}
'''

[tasks.dev-job]
description = "Build and run job"
category = "Petshop"
workspace = false
script = '''
echo Running petshop_server --job
cargo run --bin petshop_server -- --job ${@}
'''

[tasks.dev-server-release]
description = "Build and run server docker image"
category = "Petshop"
workspace = false
dependencies = [
    "docker-build"
]
script = '''
echo Running petshop/server:latest
docker run --rm -it --network=host petshop/server:latest
'''

[tasks.dev-client-playground]
description = "Build and run client-playground using node-tools image"
category = "Petshop"
workspace = false
dependencies = [
    "generate-client-flow"
]
script = '''
echo Running node-tools/client-playground
cargo make node-tools -- npm run client-playground
'''

[tasks.dev-integration-test]
description = "Build and run integration-test using node-tools image"
category = "Petshop"
workspace = false
dependencies = [
    "generate-client-flow"
]
script = '''
echo Running node-tools/integration-test
cargo make node-tools -- npm run integration-test
'''

# Docker compose tasks

[tasks.compose]
description = "Run docker-compose with default compose file"
category = "Petshop"
workspace = false
script = '''
docker-compose ${@}
'''

[tasks.compose-ci]
description = "Build generated outputs and run docker-compose with CI compose file"
category = "Petshop"
workspace = false
dependencies = [
    "docker-build-tools",
    "docker-build-rust-cache",
    "generate-flow"
]
script = '''
docker-compose -f docker-compose.ci.yml ${@}
'''

[tasks.compose-ci-down]
description = "Stop and remove docker-compose with CI compose file"
category = "Petshop"
workspace = false
script = '''
docker-compose -f docker-compose.ci.yml down
'''

# Distribution tasks

[tasks.dist-clean-images]
description = "Clean docker images"
category = "Petshop"
workspace = false
script = '''
docker image rm -f \
    petshop-auth/client-oauth2-proxy:latest \
    petshop-auth/envoy:latest \
    petshop-auth/server-oauth2-proxy:latest \
    petshop-cron/cron:latest \
    petshop/client-playground:latest \
    petshop/integration-test:latest \
    petshop/envoy:latest \
    petshop/envoy-localhost:latest \
    petshop/go-tools:latest \
    petshop/node-tools:latest \
    petshop/oauth2-proxy:latest \
    petshop/prometheus:latest \
    petshop/rust-cache:latest \
    petshop/rust-tools:latest \
    petshop/server:latest
'''

[tasks.dist-clean]
description = "Clean generated outputs"
category = "Petshop"
workspace = false
dependencies = [
    "clean"
]
script = '''
rm -rf ./dist
'''

[tasks.dist-version]
description = "Set crate and other version numbers"
category = "Petshop"
workspace = false
script = '''
echo Setting version to ${@}
export VERSION=${@}
sed -i -e "s/^version = .*/version = \"${VERSION}\"/" proto/Cargo.toml
sed -i -e "s/^version = .*/version = \"${VERSION}\"/" server/Cargo.toml
sed -i -e "s/^  CURRENT_VERSION: .*/  CURRENT_VERSION: \"${VERSION}\"/" .github/workflows/ci.yml
'''

[tasks.dist-build]
description = "Build all docker images and generated outputs"
category = "Petshop"
workspace = false
dependencies = [
    "docker-build",
    "generate-flow"
]

[tasks.dist-clients-src]
description = "Compress generated definitions and clients into file"
category = "Petshop"
workspace = false
script = '''
rm -rf ./dist/clients-src.tgz
(cd ./dist && tar -cvzf clients-src.tgz data axios grpc-web ng-swagger ngx-grpc)
'''

[tasks.dist-ci-build]
description = "Build server and envoy docker images"
category = "Petshop"
workspace = false
dependencies = [
    "docker-build-tools",
    "docker-build-rust-cache",
    "docker-build-server",
    "generate-envoy-flow",
    "generate-client-flow-pre",
    "dist-clients-src"
]

# Default tasks

[tasks.format]
[tasks.format-toml]
[tasks.clippy]
[tasks.check]
[tasks.audit]
[tasks.docs]
[tasks.dev-test-flow]
[tasks.test-flow]
[tasks.ci-flow]

[tasks.print-cargo-make-env]
[tasks.print-project-env]
[tasks.print-ci-env]
[tasks.print-git-env]
[tasks.print-rust-env]
[tasks.print-cargo-env]
[tasks.print-crate-env]
[tasks.print-env]
category = "Petshop"
workspace = false
dependencies = [
    "print-cargo-make-env",
    "print-project-env",
    "print-ci-env",
    "print-git-env",
    "print-rust-env",
    "print-cargo-env",
    "print-crate-env"
]
