# depend: docker pull envoyproxy/envoy:v1.17.0
# <https://hub.docker.com/r/envoyproxy/envoy>
FROM envoyproxy/envoy:v1.17.0

COPY ./docker/envoy/envoy.yaml /etc/envoy/envoy.yaml
COPY ./dist/api.pb /etc/envoy/api.pb
