version: "3"
services:
  # Client oauth2 proxy service
  client-oauth2-proxy:
    build:
      context: .
      dockerfile: client-oauth2-proxy.dockerfile
    image: petshop-auth/client-oauth2-proxy:latest
    ports:
      - 4180:4180

  # Server oauth2 proxy service
  server-oauth2-proxy:
    build:
      context: .
      dockerfile: server-oauth2-proxy.dockerfile
    image: petshop-auth/server-oauth2-proxy:latest

  # Prometheus service
  prometheus:
    build:
      context: .
      dockerfile: prometheus.dockerfile
    image: petshop-auth/prometheus:latest
    ports:
      - 9090:9090

  # Envoy service
  envoy:
    build:
      context: .
      dockerfile: envoy.dockerfile
    image: petshop-auth/envoy:latest
    ports:
      - 10000:10000
      - 10001:10001

  # Server service
  server:
    image: petshop/server:latest
