global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "client-oauth2-proxy"
    static_configs:
      - targets: ["client-oauth2-proxy:5180"]

  - job_name: "server-oauth2-proxy"
    static_configs:
      - targets: ["server-oauth2-proxy:5180"]

  - job_name: "envoy"
    metrics_path: "/stats/prometheus"
    static_configs:
      - targets: ["envoy:9901"]

  - job_name: "server"
    static_configs:
      - targets: ["server:5501"]
